### ISSUE TITLE
Typo in Midsourcing docs

### ISSUE THREAD

**Issue by co60ca** [AdobeDocs/campaign-classic.en#23] opened 2020-09-17 15:13 UTC
Issue in ./help/installation/using/mid-sourcing-server.md

"Click the link Use this platform as a platform to access the tracking servers"

should be 

Click the link Use this platform as a proxy to access the tracking servers ,

**Comment by Alicesnk** [comment] 2020-09-25 19:25
thanks for your feedback - the issue is now fixed

**Closed by Alicesnk** 2020-09-25 19:25 UTC
